_reference_os: &reference_os
  linux
_reference_arch: &reference_arch
  amd64
_reference_jdk: &reference_jdk
  JDK="adopt@1.11"


language: minimal # java altrimenti nada windows

git:
  depth: false # Accepts false or any number representing the commit count, defaults to 50
  autocrlf: input # Prevents git from trying to be smart with line endings

os:
  - *reference_os
  - osx
  - windows

dist: focal # esempio: per scegliere la versione di linux

arch:
  - *reference_arch
  - arm64

env:
  global: # variabili che saranno presenti in tutte le build
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git" # Convenience variable for shortening commands
    - GRAVIS="$HOME/gravis" # Convenience variable for shortening commands
    - JDK="adopt@1.11.0-8" # Partial versions supported, adopt@1.11 would pull the latest adopt 1.11
  matrix: # variabili prese in modo selettivo, questa ci da 6 jdk
    - *reference_jdk
    - JDK="adopt@1.8"
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.14"

stages:
  - check
  - test # esiste già, se non lo metto check verrebbe eseguito dopo test

_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_jdk

jobs: #usata per indicare condizioni per i quali certi jobs vengono esclusi o aggiunti
  exclude:
    - arch: arm64
      env: JDK="adopt-openj9@1.8"
    - arch: arm64
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine # metto qua dentro la cosa puntata da refmachine
      stage: check
  include: # i job messi nell'include fanno override di quelli definiti nel comportamento generale
    - <<: *reference_machine
      stage: check
      script:
        - travis_retry ./gradlew check


before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS # Check out the script set
  - source $GRAVIS/install-jdk # Install the JDK you configured in the $JDK environment variable

install:
  - true # disable install

script:
  - travis_retry ./gradlew test