language: java

git:
  depth: false # Accepts false or any number representing the commit count, defaults to 50
  autocrlf: input # Prevents git from trying to be smart with line endings

script:
  - ./gradlew check # da problemi permessi via windows, altrimenti git update-index --chmod=+x gradlew, altrimenti scrivo sh gradlew check
